syntax = "proto3";

package UserService;

// Import the request and response types
import "request/user-service-request.proto"; 
import "response/user-service-response.proto";


// User service definition
service UserService {
    rpc CreateUser(UserServiceRequest.CreateUserRequest) returns (UserServiceResponse.CreateUserResponse);
    rpc GetUserDetails(UserServiceRequest.GetUserDetailsRequest) returns (UserServiceResponse.GetUserDetailsResponse);
    rpc UpdateUser(UserServiceRequest.UpdateUserRequest) returns (UserServiceResponse.UpdateUserResponse);
}